version: "3.8"

services:
  # custom image
  app_realstate:
    build:
      args:
        user: davi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: daviux/laravel-app-real-state
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    networks:
      - docker-laravel-realstate
  
  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel-realstate

  # db
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - docker-laravel-realstate
  
networks:
  docker-laravel-realstate:
    driver: bridge